apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              name: http
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: DB_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: ORDER_SERVICE_URL
            - name: DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: DDL_AUTO
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: LOG_LEVEL
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: JAVA_OPTS
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-service-secret
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

