apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: catalog-service
  labels:
    app: catalog-service
data:
  DB_URL: "jdbc:postgresql://host.docker.internal:5433/catalogdb"
  DDL_AUTO: "validate"
  SHOW_SQL: "false"
  POOL_SIZE: "10"
  LOG_LEVEL: "INFO"
  SQL_LOG_LEVEL: "WARN"
  JAVA_OPTS: "-Xmx512m -Xms256m"

